"ultisnips ==============================================================================
" install plugin 安装插件
source ~/.vim/config/vimrc.bundle

" ==============================================================================
" 载入vim基础配置
source ~/.vim/config/vimrc.base

" 载入fcitx
source ~/.vim/config/fcitx

" ==============================================================================
" 载入vim插件配置
source ~/.vim/config/plugin_config/ag.vim
source ~/.vim/config/plugin_config/airline.vim
source ~/.vim/config/plugin_config/auto-pairs.vim
source ~/.vim/config/plugin_config/autopep8.vim
source ~/.vim/config/plugin_config/ctrlp.vim
source ~/.vim/config/plugin_config/easymotion.vim
source ~/.vim/config/plugin_config/indentline.vim
source ~/.vim/config/plugin_config/markdown.vim
source ~/.vim/config/plugin_config/multiple-cursors.vim
" source ~/.vim/config/plugin_config/neocomplete.vim
source ~/.vim/config/plugin_config/nerdcommenter.vim
source ~/.vim/config/plugin_config/nerdtree-git.vim
source ~/.vim/config/plugin_config/nerdtree-tab.vim
source ~/.vim/config/plugin_config/nerdtree.vim
source ~/.vim/config/plugin_config/python-auto.vim
source ~/.vim/config/plugin_config/quick-scope.vim
source ~/.vim/config/plugin_config/syntastic.vim
source ~/.vim/config/plugin_config/tagbar.vim
source ~/.vim/config/plugin_config/ultisnips.vim
source ~/.vim/config/plugin_config/ycm.vim
source ~/.vim/config/plugin_config/cscope_maps.vim
" source ~/.vim/config/plugin_config/vimwiki.vim
